services:
  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - spring-microservice

networks:
  spring-microservice:
    driver: bridge
